### ISSUE TITLE
Can I do strategies that involve buying stocks and receiving dividends?

### ISSUE THREAD

**Issue by michael-erasmus** [hashABCD/opstrat#2]
Great package! I been curious to use this to visualize strategies like writing covered calls, and also take into account dividend payments. Is that possible?

**Comment by hashABCD** [comment]
Thank you for the feedback: 

a. Covered Call:
As of now combinations of option contracts with same expiration date are only possible to plot. 
Future/stock purchase/sale  will be added soon. After that covered call can be visualized.

b. Effect of Dividend
Dividend payment does not have any direct impact on payoff diagrams. (as option premium is entered for single and multiplotter and real-time option premium is fetched in yf_plotter)

Option pricing:
A major assumption of Black Scholes model is that the stocks are not dividend paying. 
There are modifications of BSM which consider the effect of dividend in Option Premium. 
black_scholes module of opstrat package can be used to calculate option premium, but dividend effect is not included.
It may be incorporated in the future, you can clone the repo and add the code required. 
Dividends, however, do not have significant impact on option premium.

Cheers!

**Comment by michael-erasmus** [comment]
Thanks for the answers @hashABCD! I'll go ahead and close the issue if that's ok

> Future/stock purchase/sale will be added soon. After that covered call can be visualized.

Looking forward to that!

**Comment by pinpss** [comment]
Any updates on this? Thanks
